-- UPDATE statements for fi.parametros table
-- Generated from parametrosv2.csv data

UPDATE fi.parametros SET prmt_codigo = 'DIAS_DEL_PERIODO', prmt_desc = 'días del periodo', prmt_valor = 365.000, prmt_ano = NULL WHERE prmt_id = 10000;
UPDATE fi.parametros SET prmt_codigo = 'EV_ABR', prmt_desc = 'estacionalidad ventas', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 10001;
UPDATE fi.parametros SET prmt_codigo = 'UNID_MED', prmt_desc = 'unidad medida', prmt_valor = 1000.000, prmt_ano = NULL WHERE prmt_id = 10002;
UPDATE fi.parametros SET prmt_codigo = 'PROY_UTIL', prmt_desc = 'proyeccion utilidad', prmt_valor = 0.800, prmt_ano = 2025 WHERE prmt_id = 10003;
UPDATE fi.parametros SET prmt_codigo = 'PROY_UTIL', prmt_desc = 'proyeccion utilidad', prmt_valor = 0.850, prmt_ano = 2026 WHERE prmt_id = 10004;
UPDATE fi.parametros SET prmt_codigo = 'PROY_UTIL', prmt_desc = 'proyeccion utilidad', prmt_valor = 0.900, prmt_ano = 2027 WHERE prmt_id = 10005;
UPDATE fi.parametros SET prmt_codigo = 'PROY_UTIL', prmt_desc = 'proyeccion utilidad', prmt_valor = 0.950, prmt_ano = 2029 WHERE prmt_id = 10006;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 5.000, prmt_ano = 2022 WHERE prmt_id = 10007;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 5.000, prmt_ano = 2023 WHERE prmt_id = 10008;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 5.000, prmt_ano = 2024 WHERE prmt_id = 10009;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 5000.000, prmt_ano = 2025 WHERE prmt_id = 10010;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 6000.000, prmt_ano = 2026 WHERE prmt_id = 10011;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 6000.000, prmt_ano = 2027 WHERE prmt_id = 10012;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 5000.000, prmt_ano = 2028 WHERE prmt_id = 10013;
UPDATE fi.parametros SET prmt_codigo = 'PROY_INVERSION', prmt_desc = 'proyeccion inversion', prmt_valor = 5000.000, prmt_ano = 2029 WHERE prmt_id = 10014;
UPDATE fi.parametros SET prmt_codigo = 'RD', prmt_desc = 'rd ', prmt_valor = 7.200, prmt_ano = NULL WHERE prmt_id = 10015;
UPDATE fi.parametros SET prmt_codigo = 'RE', prmt_desc = 'r estacionalidad', prmt_valor = 13.200, prmt_ano = NULL WHERE prmt_id = 10016;
UPDATE fi.parametros SET prmt_codigo = 'WACC', prmt_desc = 'wacc', prmt_valor = 11.600, prmt_ano = NULL WHERE prmt_id = 10017;
UPDATE fi.parametros SET prmt_codigo = 'GRL', prmt_desc = '', prmt_valor = 11.600, prmt_ano = 2023 WHERE prmt_id = 20001;
UPDATE fi.parametros SET prmt_codigo = 'MANT', prmt_desc = '', prmt_valor = 11.600, prmt_ano = 2023 WHERE prmt_id = 20003;
UPDATE fi.parametros SET prmt_codigo = 'HON', prmt_desc = '', prmt_valor = 11.600, prmt_ano = 2023 WHERE prmt_id = 20004;
UPDATE fi.parametros SET prmt_codigo = 'TASA CP', prmt_desc = '', prmt_valor = 0.058, prmt_ano = NULL WHERE prmt_id = 30001;
UPDATE fi.parametros SET prmt_codigo = 'TASA LP', prmt_desc = '', prmt_valor = 0.060, prmt_ano = NULL WHERE prmt_id = 30002;
UPDATE fi.parametros SET prmt_codigo = 'SPREAD', prmt_desc = '', prmt_valor = 0.012, prmt_ano = NULL WHERE prmt_id = 30003;
UPDATE fi.parametros SET prmt_codigo = 'BETA', prmt_desc = '', prmt_valor = 0.012, prmt_ano = NULL WHERE prmt_id = 30004;
UPDATE fi.parametros SET prmt_codigo = 'CREC_RESIDUAL', prmt_desc = '', prmt_valor = 0.030, prmt_ano = NULL WHERE prmt_id = 30005;
UPDATE fi.parametros SET prmt_codigo = 'RIESGO_PAIS', prmt_desc = '', prmt_valor = 0.060, prmt_ano = NULL WHERE prmt_id = 30006;
UPDATE fi.parametros SET prmt_codigo = 'SPREAD_2', prmt_desc = '', prmt_valor = 0.010, prmt_ano = NULL WHERE prmt_id = 30007;
UPDATE fi.parametros SET prmt_codigo = 'RF', prmt_desc = '', prmt_valor = 0.060, prmt_ano = NULL WHERE prmt_id = 30008;
UPDATE fi.parametros SET prmt_codigo = 'MG_BR', prmt_desc = 'Margen Bruto', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 40001;
UPDATE fi.parametros SET prmt_codigo = 'MG_BR', prmt_desc = 'Margen Bruto', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 40002;
UPDATE fi.parametros SET prmt_codigo = 'MG_BR', prmt_desc = 'Margen Bruto', prmt_valor = 0.180, prmt_ano = 2025 WHERE prmt_id = 40003;
UPDATE fi.parametros SET prmt_codigo = 'MG_BR', prmt_desc = 'Margen Bruto', prmt_valor = 0.190, prmt_ano = 2026 WHERE prmt_id = 40004;
UPDATE fi.parametros SET prmt_codigo = 'MG_BR', prmt_desc = 'Margen Bruto', prmt_valor = 0.190, prmt_ano = 2027 WHERE prmt_id = 40005;
UPDATE fi.parametros SET prmt_codigo = 'G_V_V', prmt_desc = 'Gastos de Venta y Variables', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 40006;
UPDATE fi.parametros SET prmt_codigo = 'G_V_V', prmt_desc = 'Gastos de Venta y Variables', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 40007;
UPDATE fi.parametros SET prmt_codigo = 'G_V_V', prmt_desc = 'Gastos de Venta y Variables', prmt_valor = 0.000, prmt_ano = 2025 WHERE prmt_id = 40008;
UPDATE fi.parametros SET prmt_codigo = 'G_V_V', prmt_desc = 'Gastos de Venta y Variables', prmt_valor = 0.000, prmt_ano = 2026 WHERE prmt_id = 40009;
UPDATE fi.parametros SET prmt_codigo = 'G_V_V', prmt_desc = 'Gastos de Venta y Variables', prmt_valor = 0.000, prmt_ano = 2027 WHERE prmt_id = 40010;
UPDATE fi.parametros SET prmt_codigo = 'G_A_V', prmt_desc = 'Gastos de Administracion y Ventas', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 40011;
UPDATE fi.parametros SET prmt_codigo = 'G_A_V', prmt_desc = 'Gastos de Administracion y Ventas', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 40012;
UPDATE fi.parametros SET prmt_codigo = 'G_A_V', prmt_desc = 'Gastos de Administracion y Ventas', prmt_valor = 0.025, prmt_ano = 2025 WHERE prmt_id = 40013;
UPDATE fi.parametros SET prmt_codigo = 'G_A_V', prmt_desc = 'Gastos de Administracion y Ventas', prmt_valor = 0.025, prmt_ano = 2026 WHERE prmt_id = 40014;
UPDATE fi.parametros SET prmt_codigo = 'G_A_V', prmt_desc = 'Gastos de Administracion y Ventas', prmt_valor = 0.025, prmt_ano = 2027 WHERE prmt_id = 40015;
UPDATE fi.parametros SET prmt_codigo = 'IMPTO', prmt_desc = 'Impuesto', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 40016;
UPDATE fi.parametros SET prmt_codigo = 'IMPTO', prmt_desc = 'Impuesto', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 40017;
UPDATE fi.parametros SET prmt_codigo = 'IMPTO', prmt_desc = 'Impuesto', prmt_valor = 0.270, prmt_ano = 2025 WHERE prmt_id = 40018;
UPDATE fi.parametros SET prmt_codigo = 'IMPTO', prmt_desc = 'Impuesto', prmt_valor = 0.270, prmt_ano = 2026 WHERE prmt_id = 40019;
UPDATE fi.parametros SET prmt_codigo = 'IMPTO', prmt_desc = 'Impuesto', prmt_valor = 0.270, prmt_ano = 2027 WHERE prmt_id = 40020;
UPDATE fi.parametros SET prmt_codigo = 'CAJA', prmt_desc = 'Caja', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 50001;
UPDATE fi.parametros SET prmt_codigo = 'CAJA', prmt_desc = 'Caja', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 50002;
UPDATE fi.parametros SET prmt_codigo = 'CAJA', prmt_desc = 'Caja', prmt_valor = 10.000, prmt_ano = 2025 WHERE prmt_id = 50003;
UPDATE fi.parametros SET prmt_codigo = 'CAJA', prmt_desc = 'Caja', prmt_valor = 10.000, prmt_ano = 2026 WHERE prmt_id = 50004;
UPDATE fi.parametros SET prmt_codigo = 'CAJA', prmt_desc = 'Caja', prmt_valor = 10.000, prmt_ano = 2027 WHERE prmt_id = 50005;
UPDATE fi.parametros SET prmt_codigo = 'CXC', prmt_desc = 'Cuentas por Cobrar', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 50006;
UPDATE fi.parametros SET prmt_codigo = 'CXC', prmt_desc = 'Cuentas por Cobrar', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 50007;
UPDATE fi.parametros SET prmt_codigo = 'CXC', prmt_desc = 'Cuentas por Cobrar', prmt_valor = 110.000, prmt_ano = 2025 WHERE prmt_id = 50008;
UPDATE fi.parametros SET prmt_codigo = 'CXC', prmt_desc = 'Cuentas por Cobrar', prmt_valor = 110.000, prmt_ano = 2026 WHERE prmt_id = 50009;
UPDATE fi.parametros SET prmt_codigo = 'CXC', prmt_desc = 'Cuentas por Cobrar', prmt_valor = 110.000, prmt_ano = 2027 WHERE prmt_id = 50010;
UPDATE fi.parametros SET prmt_codigo = 'EXIST', prmt_desc = 'Existencias', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 50011;
UPDATE fi.parametros SET prmt_codigo = 'EXIST', prmt_desc = 'Existencias', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 50012;
UPDATE fi.parametros SET prmt_codigo = 'EXIST', prmt_desc = 'Existencias', prmt_valor = 0.000, prmt_ano = 2025 WHERE prmt_id = 50013;
UPDATE fi.parametros SET prmt_codigo = 'EXIST', prmt_desc = 'Existencias', prmt_valor = 0.000, prmt_ano = 2026 WHERE prmt_id = 50014;
UPDATE fi.parametros SET prmt_codigo = 'EXIST', prmt_desc = 'Existencias', prmt_valor = 0.000, prmt_ano = 2027 WHERE prmt_id = 50015;
UPDATE fi.parametros SET prmt_codigo = 'CXP', prmt_desc = 'Cuentas por Pagar', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 50016;
UPDATE fi.parametros SET prmt_codigo = 'CXP', prmt_desc = 'Cuentas por Pagar', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 50017;
UPDATE fi.parametros SET prmt_codigo = 'CXP', prmt_desc = 'Cuentas por Pagar', prmt_valor = 40.000, prmt_ano = 2025 WHERE prmt_id = 50018;
UPDATE fi.parametros SET prmt_codigo = 'CXP', prmt_desc = 'Cuentas por Pagar', prmt_valor = 40.000, prmt_ano = 2026 WHERE prmt_id = 50019;
UPDATE fi.parametros SET prmt_codigo = 'CXP', prmt_desc = 'Cuentas por Pagar', prmt_valor = 40.000, prmt_ano = 2027 WHERE prmt_id = 50020;
UPDATE fi.parametros SET prmt_codigo = 'REM', prmt_desc = 'Remuneraciones', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60001;
UPDATE fi.parametros SET prmt_codigo = 'REM', prmt_desc = 'Remuneraciones', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60002;
UPDATE fi.parametros SET prmt_codigo = 'REM', prmt_desc = 'Remuneraciones', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60003;
UPDATE fi.parametros SET prmt_codigo = 'REM', prmt_desc = 'Remuneraciones', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60004;
UPDATE fi.parametros SET prmt_codigo = 'REM', prmt_desc = 'Remuneraciones', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60005;
UPDATE fi.parametros SET prmt_codigo = 'GPER', prmt_desc = 'Gastos de Personal', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60006;
UPDATE fi.parametros SET prmt_codigo = 'GPER', prmt_desc = 'Gastos de Personal', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60007;
UPDATE fi.parametros SET prmt_codigo = 'GPER', prmt_desc = 'Gastos de Personal', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60008;
UPDATE fi.parametros SET prmt_codigo = 'GPER', prmt_desc = 'Gastos de Personal', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60009;
UPDATE fi.parametros SET prmt_codigo = 'GPER', prmt_desc = 'Gastos de Personal', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60010;
UPDATE fi.parametros SET prmt_codigo = 'SERV', prmt_desc = 'Servicios', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60011;
UPDATE fi.parametros SET prmt_codigo = 'SERV', prmt_desc = 'Servicios', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60012;
UPDATE fi.parametros SET prmt_codigo = 'SERV', prmt_desc = 'Servicios', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60013;
UPDATE fi.parametros SET prmt_codigo = 'SERV', prmt_desc = 'Servicios', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60014;
UPDATE fi.parametros SET prmt_codigo = 'SERV', prmt_desc = 'Servicios', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60015;
UPDATE fi.parametros SET prmt_codigo = 'MAT', prmt_desc = 'Materiales', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60016;
UPDATE fi.parametros SET prmt_codigo = 'MAT', prmt_desc = 'Materiales', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60017;
UPDATE fi.parametros SET prmt_codigo = 'MAT', prmt_desc = 'Materiales', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60018;
UPDATE fi.parametros SET prmt_codigo = 'MAT', prmt_desc = 'Materiales', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60019;
UPDATE fi.parametros SET prmt_codigo = 'MAT', prmt_desc = 'Materiales', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60020;
UPDATE fi.parametros SET prmt_codigo = 'ARR', prmt_desc = 'Arriendos', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60021;
UPDATE fi.parametros SET prmt_codigo = 'ARR', prmt_desc = 'Arriendos', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60022;
UPDATE fi.parametros SET prmt_codigo = 'ARR', prmt_desc = 'Arriendos', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60023;
UPDATE fi.parametros SET prmt_codigo = 'ARR', prmt_desc = 'Arriendos', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60024;
UPDATE fi.parametros SET prmt_codigo = 'ARR', prmt_desc = 'Arriendos', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60025;
UPDATE fi.parametros SET prmt_codigo = 'DEP', prmt_desc = 'Depreciacion', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60026;
UPDATE fi.parametros SET prmt_codigo = 'DEP', prmt_desc = 'Depreciacion', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60027;
UPDATE fi.parametros SET prmt_codigo = 'DEP', prmt_desc = 'Depreciacion', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60028;
UPDATE fi.parametros SET prmt_codigo = 'DEP', prmt_desc = 'Depreciacion', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60029;
UPDATE fi.parametros SET prmt_codigo = 'DEP', prmt_desc = 'Depreciacion', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60030;
UPDATE fi.parametros SET prmt_codigo = 'HERR', prmt_desc = 'Herramientas', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60031;
UPDATE fi.parametros SET prmt_codigo = 'HERR', prmt_desc = 'Herramientas', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60032;
UPDATE fi.parametros SET prmt_codigo = 'HERR', prmt_desc = 'Herramientas', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60033;
UPDATE fi.parametros SET prmt_codigo = 'HERR', prmt_desc = 'Herramientas', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60034;
UPDATE fi.parametros SET prmt_codigo = 'HERR', prmt_desc = 'Herramientas', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60035;
UPDATE fi.parametros SET prmt_codigo = 'OTR', prmt_desc = 'Otros', prmt_valor = 0.100, prmt_ano = 2023 WHERE prmt_id = 60036;
UPDATE fi.parametros SET prmt_codigo = 'OTR', prmt_desc = 'Otros', prmt_valor = 0.100, prmt_ano = 2024 WHERE prmt_id = 60037;
UPDATE fi.parametros SET prmt_codigo = 'OTR', prmt_desc = 'Otros', prmt_valor = 0.100, prmt_ano = 2025 WHERE prmt_id = 60038;
UPDATE fi.parametros SET prmt_codigo = 'OTR', prmt_desc = 'Otros', prmt_valor = 0.100, prmt_ano = 2026 WHERE prmt_id = 60039;
UPDATE fi.parametros SET prmt_codigo = 'OTR', prmt_desc = 'Otros', prmt_valor = 0.100, prmt_ano = 2027 WHERE prmt_id = 60040;
UPDATE fi.parametros SET prmt_codigo = 'ENE', prmt_desc = 'Enero', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70001;
UPDATE fi.parametros SET prmt_codigo = 'FEB', prmt_desc = 'Febrero', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70002;
UPDATE fi.parametros SET prmt_codigo = 'MAR', prmt_desc = 'Marzo', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70003;
UPDATE fi.parametros SET prmt_codigo = 'ABR', prmt_desc = 'Abril', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70004;
UPDATE fi.parametros SET prmt_codigo = 'MAY', prmt_desc = 'Mayo', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70005;
UPDATE fi.parametros SET prmt_codigo = 'JUN', prmt_desc = 'Junio', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70006;
UPDATE fi.parametros SET prmt_codigo = 'JUL', prmt_desc = 'Julio', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70007;
UPDATE fi.parametros SET prmt_codigo = 'AGO', prmt_desc = 'Agosto', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70008;
UPDATE fi.parametros SET prmt_codigo = 'SEPT', prmt_desc = 'Septiembre', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70009;
UPDATE fi.parametros SET prmt_codigo = 'OCT', prmt_desc = 'Octubre', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70010;
UPDATE fi.parametros SET prmt_codigo = 'NOV', prmt_desc = 'Noviembre', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70011;
UPDATE fi.parametros SET prmt_codigo = 'DIC', prmt_desc = 'Diciembre', prmt_valor = 0.100, prmt_ano = NULL WHERE prmt_id = 70012;
UPDATE fi.parametros SET prmt_codigo = 'PROY_CRECIMIENTO', prmt_desc = 'proyeccion crecimiento de ventas', prmt_valor = 0.150, prmt_ano = 2025 WHERE prmt_id = 80001;
UPDATE fi.parametros SET prmt_codigo = 'PROY_CRECIMIENTO', prmt_desc = 'proyeccion crecimiento de ventas', prmt_valor = 0.200, prmt_ano = 2026 WHERE prmt_id = 80002;
UPDATE fi.parametros SET prmt_codigo = 'PROY_CRECIMIENTO', prmt_desc = 'proyeccion crecimiento de ventas', prmt_valor = 0.050, prmt_ano = 2027 WHERE prmt_id = 80003;
UPDATE fi.parametros SET prmt_codigo = 'PROY_CREDITO_NETO', prmt_desc = 'proyeccion credito neto', prmt_valor = 4000.000, prmt_ano = 2025 WHERE prmt_id = 80004;
UPDATE fi.parametros SET prmt_codigo = 'PROY_CREDITO_NETO', prmt_desc = 'proyeccion credito neto', prmt_valor = 3500.000, prmt_ano = 2026 WHERE prmt_id = 80005;
UPDATE fi.parametros SET prmt_codigo = 'PROY_CREDITO_NETO', prmt_desc = 'proyeccion credito neto', prmt_valor = 4000.000, prmt_ano = 2027 WHERE prmt_id = 80006;
UPDATE fi.parametros SET prmt_codigo = 'PROY_DIVIDENDOS', prmt_desc = 'proyeccion dividendos', prmt_valor = 5100.000, prmt_ano = 2025 WHERE prmt_id = 80007;
UPDATE fi.parametros SET prmt_codigo = 'PROY_DIVIDENDOS', prmt_desc = 'proyeccion dividendos', prmt_valor = 5300.000, prmt_ano = 2026 WHERE prmt_id = 80008;
UPDATE fi.parametros SET prmt_codigo = 'PROY_DIVIDENDOS', prmt_desc = 'proyeccion dividendos', prmt_valor = 6000.000, prmt_ano = 2027 WHERE prmt_id = 80009;
UPDATE fi.parametros SET prmt_codigo = 'VRA', prmt_desc = 'vida residual activos', prmt_valor = 0.400, prmt_ano = NULL WHERE prmt_id = 90001;
UPDATE fi.parametros SET prmt_codigo = 'VUC', prmt_desc = 'vida util activos', prmt_valor = 20.000, prmt_ano = NULL WHERE prmt_id = 90002; 